### ISSUE TITLE
Some immediate tasks for Carat

### ISSUE THREAD

**Issue by olexandr-konovalov** [lbfm-rwth/carat#1]
After the establishing of this repository, what would be useful to do before starting further modifications of the code:
- [x] convert README to Markdown and add CI badges #17 
- [ ] establish carat website based on GitHub pages
- [x] Add LICENSE file
- [ ] Add CITATION file
- [x] ensure that carat compiles
- [x] add `configure` script
- [ ] check issues from https://github.com/gap-packages/carat/issues, resolve or migrate them, and make a new release
  - [x] incompatible file names for Windows https://github.com/gap-packages/carat/issues/5 
  - [ ] multiple compiler warnings https://github.com/gap-packages/carat/issues/7
- [x] add regression tests #6
- [x] add Travis CI integration for builds on Linux and macOS #3
- [x] add Codecov integration to gather code coverage reports #6 
- [x] add AppVeyor integration for builds on Windows (cygwin 32 and 64 bit) #13 
- [ ] establish ChangeLog file #15

**Comment by alex-konovalov** [comment]
Now since the new website works, one could add its URL to the README, and also setup the description and the URL for this repository.

**Comment by fingolfin** [comment]
@gaehler @DominikBernhardt do you have any idea about the licensing situation for this code?

**Comment by DominikBernhardt** [comment]
As far as the Carat code itself is concerned it was developed at RWTH under the supervision of Plesken and he told me I can change it and do with it what I want to improve it / get it on GitHub etc. So not sure which licence I should put..

**Comment by fingolfin** [comment]
Well, this would be IMHO rather important to resolve, as strictly speaking, code without any license cannot be used or distributed legally by anybody other than the copyright holder.

Perhaps you can ask him if he would be willing to put this code under the GPL, or some other open source license?

**Comment by alex-konovalov** [comment]
Thanks to @jamesjer, it seems we have found the lost COPYING file. @DominikBernhardt I know that you're very busy, but most of the critical tasks are not touching mathematical functionality of Carat, hopefully we may try to release in update all together? @gaehler would certainly like using new Carat in the GAP package.

**Comment by gaehler** [comment]
I did make a new release of my GAP package, bundling yesterdays GitHub version of CARAT, in order to get it into GAP 4.11. I can of course iterate this whenever there are significant improvements to CARAT, whether or not there is a formal release. Adding back the `COPYING` file would be good, and also replacing `tex/index.html` by a the current version with the corrected statistics in dimension 6 (I have found a copy of this file).
